### PR TITLE
Srh group8

### PR DESCRIPTION
**Pull request by vickyvishal**
Replacing BaselineClassifier with DummyClassifier from sklearn.
Relacing BaselineRegressor with DummyRegressor from sklearn.

Contributed by students of SRH University, Heidelberg.
https://github.com/tauseefhashmi
https://github.com/frankcode101
https://github.com/tanmaygaikwad
https://github.com/RajathReddy9
https://github.com/vickyvishal/

### CODE REVIEW

**Comment by shinnar** [comment]
thanks for your interest in Lale, and for working on this issue.

Lale has a slightly different approach to exposing operators.  Generally, we don't copy the implementation from underlying libraries like sklearn, but instead take the underlying operators, write schemas for them (which clarify what values the hyper-parameters can have, as well the input and output types), and tied them together.

An example is LogisticRegression: https://github.com/IBM/lale/blob/master/lale/lib/sklearn/logistic_regression.py
after declaring the appropriate schemas, they are tied together with the sklearn implementation in the make_operator call:
https://github.com/IBM/lale/blob/master/lale/lib/sklearn/logistic_regression.py#L419

We have a notebook that attempts to guide one through this process:
https://github.com/IBM/lale/blob/master/examples/docs_new_operators.ipynb

please feel free to provide feedback/submit issues/PRs if you have suggestions for how to improve our documentation.

If you would like to try and update this PR appropriately, I would be happy to help answer questions that you may have.

**Comment by vickyvishal** [comment]
Thanks for the pointers. We are going to take a look again

**Comment by shinnar** [comment]
the static failures are due to an issue with the pre-commit checker that is being worked on.  I will comment again when it is fixed.

**Comment by shinnar** [comment]
The pre-commit issue should now be resolved. 
Please rebase against the latest master branch and run `pre-commit run -a` to ensure that all of your files are correctly formatted with the updated linter versions.

**Comment by vickyvishal** [comment]
Created a new PR

**Pull request closed without merging**
