### PR TITLE
Remove Super prefix from supertexttransformer

### PR DESCRIPTION
**Pull request by szymonkucharczyk**

### CODE REVIEW

**Comment by shinnar** [comment]
the static failures are due to an issue with the pre-commit checker that is being worked on.  I will comment again when it is fixed.

**Comment by szymonkucharczyk** [comment]
Thank You!

**Comment by shinnar** [comment]
The issue should now be resolved.  Please rebase against the latest master branch and run `pre-commit run -a` to ensure that all of your files are correctly formatted with the updated linter versions.

**Comment by szymonkucharczyk** [comment]
There may occur some import errors as valid autoai-libs are still on the feature branch

**Comment by szymonkucharczyk** [comment]
@shinnar  I've run the failing test locally with the autoai-libs from test pypi (1.12.6.2) and it run successfully. Although, to make an official release of core and libs we would like to test everything together with lale. Is there any possibility to make a test pypi lale release from my fork ?

**Comment by szymonkucharczyk** [comment]
Locally the tests work for me fine with latest autoai-libs from prod pypi (1.12.6, https://pypi.org/project/autoai-libs/). I can see in the install dependencies section of failing tests that the latest autoai-libs version is not installed:
` Requirement already satisfied: autoai-libs in /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages (from lale==0.4.15) (1.12.5)`
Should I add a requirement to autoai-libs >=1.12.6 ?

**Comment by shinnar** [comment]
yes, that makes sense.

**Pull request merged**
