### PR TITLE
Out Scripts are Optimized in the Importing Task

### PR DESCRIPTION
**Pull request by lnxpy**
`isort` module observed on the outer scripts. So that neither `search/*.py`, `lib/*.py`, `datasets/*.py`, and `utils/*.py` have been changed which means that the `schema2search_space.py` file is still like the usual.

### CODE REVIEW

**Comment by hirzel** [comment]
Thanks, happy to see that this version passes Travis. Also, I read through the code changes, and they look good to me. Could you please sign a DCO as outlined in [contributing.md](https://github.com/IBM/lale/blob/master/CONTRIBUTING.md)? You can email it to me: hirzel at us dot ibm dot com.

**Comment by lnxpy** [comment]
That's my pleasure. Should I send the DCO doc back to you? Is it enough or any other significant required?

**Comment by hirzel** [comment]
Yes, could you please email the signed DCO back to me?

**Comment by lnxpy** [comment]
Everything is done. Special thanks to you for checking out the PRs. Really appreciate your attention. I really amazed by the name of the project; just because my native language is Persian. :heart: :v:

**Comment by lnxpy** [comment]
Hey dear @hirzel,
Do you mind if I ask you to first, review this PR and finally, add the "hacktoberfest" label to this pull request?
Thanks.

**Review by hirzel — COMMENTED** [review]
The changes sort import statements in Python files that are directly in the main `lale` directory. There are no changes to the code outside of those import statements. The Travis tests succeeded.

**Comment by lnxpy** [comment]
Thanks. I'll contribute to the main algorithm and add new features soon.

**Comment by shinnar** [comment]
thanks for contributing this and getting this started!  Continuing on this work, https://github.com/IBM/lale/pull/481 resolved the issue with schema2search_space.py, ran isort on everything, and added `isort` to our new pre-commit setup.

**Pull request merged**
