### PR TITLE
remove_last returns the pipeline, so we can call freeze_trainable on it.

### PR DESCRIPTION
**Pull request by kiran-kate**

### CODE REVIEW

**Comment by hirzel** [comment]
I had not caught this before. Could we please keep the original pipeline immutable? In other words, remove_last returns a new pipeline that is the same as the old one but without the last step. At the same time, the old pipeline also still exists and still has its last step.

**Comment by kiran-kate** [comment]
I had thought about it, but thought it would be expensive, specially if the pipeline contains some neural network operators. This is not the majority case right now though.

**Comment by kiran-kate** [comment]
What if we add an optional parameter to `remove_last` to give a boolean choice of `inplace`. The default can be False and it can be True if that is so desired.

**Comment by hirzel** [comment]
I like the inplace `argument` with the `False` default.

**Pull request merged**
