### PR TITLE
Prefix snapml estimators with 'Snap'

### PR DESCRIPTION
**Pull request by tdoublep**
Inside autoai_core, estimators are identified by their class name (rather than a full path include the module etc). 
While there does not seem to be any limitation on the Lale side related to having multiple estimators with the same class name, it looks like significant changes would be required in AutoAI core in order to handle this, and these changes would propagate all the way up to the top-level interface.

In order to have smooth integration without changing the KaggleBot interface, I propose to simply prefix the snapml esimator class names with `Snap`. I've tested these changes with autoai_core development branch and everything seems to work nicely.

### CODE REVIEW

**Comment by hirzel** [comment]
Then we should also rename the file names, for example, `snap_decision_tree_classifier.py`.

**Comment by tdoublep** [comment]
@hirzel Please review when you have a moment - thank you.

**Comment by tdoublep** [comment]
> Then we should also rename the file names, for example, `snap_decision_tree_classifier.py`.

Done!

**Comment by hirzel** [comment]
Looks good, thank you!

**Pull request merged**
